{% extends "layouts/admin.phtml" %}

{% block content %}
<h3>Paginas</h3>
<a href="/admin/pages/new" class="button">Nova Pagina</a>
<hr>
<table class="table">
	<thead>
		<tr>
			<th>ID</th>
			<th>Title</th>
			<th colspan="2">Action</th>
		</tr>
	</thead>
	<tbody>

		{% for page in pages %}
		<tr>
			<td>{{ page.id }}</td>
			<td>{{ page.title }}</td>			
			<td><a href="/admin/pages/{{ page.id }}" class="button primary">Ver</a></td>			
			<td><a href="/admin/pages/edit/{{ page.id }}" class="button secondary">Editar</a></td>
			<td>
				<form action="/admin/pages/delete/{{ page.id }}" method="post">
					<input type="submit" value="Deletar" class="button error" />
				</form>
			</td>
		</tr>
		{% else %}
		<tr>
			<td colspan="4">Sem registros</td>
		</tr>		
		{% endfor %}
	</tbody>
</table>

{% endblock %}